In [2]:
x = (0,1,2,3,4)

In [9]:
product = reduce( (lambda x, y: x * y), x[1:] )
print product

24


In [24]:
print [x[1] for x in {'a':1, 'b':2}.items() if x[0][0] == 'a']

[1]


In [1]:
import numpy as np

x = np.array([[1,2,3],[3,4,6]])
print x

[[1 2 3]
 [3 4 6]]


In [15]:
print np.pad(x, ((0,0),(3,3)), 'constant', constant_values=0)

[[0 0 0 1 2 3 0 0 0]
 [0 0 0 3 4 6 0 0 0]]


In [10]:
print range(6)

[0, 1, 2, 3, 4, 5]
