In [1]:
import numpy as np

In [2]:
arr = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

In [4]:
print arr
print arr.shape
print arr[0,1,2]
print arr[1,1,2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
(2L, 2L, 3L)
6
60


In [27]:
x = np.ones([10,3])
y_pred = np.asarray(np.matrix(np.argmax(x, axis=1)))
print "original: ", y_pred.shape
print "reshape: ", y_pred.reshape((10,)).shape
print "flatten: ", y_pred.flatten().shape
print "ravel: ", y_pred.ravel().shape

original:  (1L, 10L)
reshape:  (10L,)
flatten:  (10L,)
ravel:  (10L,)
